#+TITLE: matrixcli a minimal command line matrix client
#+AUTHOR: saadnpq
#+HUGO_BASE_DIR: ~/blog/ 
#+hugo_auto_set_lastmod: t
#+EXPORT_FILE_NAME: matrixcli
#+hugo_tags: projects

matrixcli is a simple [[https://matrix.org/blog/home/][matrix]] client based on the [[https://github.com/matrix-org/matrix-python-sdk][matrix-python-sdk]]

* installation
you can install matrixcli using setup.py in root project directory. 
This will also install all needed dependencies.
#+BEGIN_SRC shell
git clone https://git.saadnpq.com/saad/matrixcli
cd ./matrixcli 
sudo ./setup.py install 
#+END_SRC
this will put the matrixcli script in your path, install a 
template config.py file in /etc/matrixcli and systemd unit file in /lib/systemd/user

if you want to test the program without installing it you 
can install the [[*dependencies][dependencies]] manually and just run ./matrixcli in the cloned repository

* dependencies 
the only required dependency is the matrix-python-sdk, which is 
installed automatically if you used the install method mentioned above.
to install it manually run the following 
#+begin_src shell
sudo pip3 install matrix_client
#+end_src

* configuration file
the account configuration is done through the config.py
file either in one of the following locations sorted by precedence

1) custom file specified using the -c option
1) $HOME/.config/matrixcli  
1) /etc/matrixcli  

this is a one account sample configuration.
#+begin_src python 
def password_eval():
    return "Y0UrPredIctabLePA$$w0ord"

accounts=[{ "server":"https://matrix.org/",
              "username":"putYourUserNameHere",
              "passeval":password_eval }] 
# the password_eval function can be named any thing as long as 
# it matches the function definition 
#+end_src 

the configuration file should have an =accounts= variable which holds 
a list of dictionaries where every dictionary consists of the account 
information server, username and password eval 

the rationale behind defining a function that returns the password value
is that if you don't want to write your password in plain text you can 
write any python code you wish that generates or reads the password from 
an encrypted file or a key ring

if you don't want to make a configuration file at all, you can pass the server, username
and password through command line arguments. see [[*usage][usage]]

** multi account configuration 

suppose you have the following configuration file
#+begin_src python 
def account1_password_eval():
    return "account1secretpassword"

def account2_matrixorg_password_eval():
    return "account2secretpassword"

def account3_password_eval_any_name():
    return "yXkdsjhslkjhdlksjhffffffkkssskjsdhkljhssdc"

accounts=[

        { "server":"https://example.com",
          "username":"account1",
          "passeval":account1_password_eval },

        { "server":"https://matrix.org",
          "username":"account2",
          "passeval":account2_matrixorg_password_eval},

        { "server":"https://example.com",
          "username":"account3",
          "passeval":account3_password_eval_any_name },]
#+end_src 

if you didn't specify any command line option, the program will use the first
account in the accounts list. to use any other account its enough to 
pass the -u or --username option to the command with the username of that account.

for example 
#+begin_src shell
matrixcli -u account3 getrooms
#+end_src
that command will login with the parameters of the third account.

if you have two or more accounts with the same username but with different servers.
you can specify the --server option to norrow down the possible accounts to the
account you want.

* usage
for a list of the sub commands and options run 
#+begin_src shell
matrixcli --help 
#+end_src
output:
#+begin_example
#usage: matrixcli [-h] [-s SERVER] [-u USERNAME] [-p PASSWORD] [-c CONFIG]
                 {send,listen,rooms,unread,tail} ...

command line matrix client

optional arguments:
  -h, --help            show this help message and exit
  -s SERVER, --server SERVER
                        server to login to
  -u USERNAME, --username USERNAME
                        username to login with
  -p PASSWORD, --password PASSWORD
                        the password
  -c CONFIG, --config CONFIG
                        custom configuration file

subcommands:
  {send,listen,rooms,unread,tail}
    send                send something to a room
    listen              listen forever for events
    rooms               get all joined rooms
    unread              get unread notifications
    tail                print last messages
#+end_example

to list the options of a specific sub command, (e.g. send)

#+begin_src shell
matrixcli send --help 
#+end_src

** rooms 
every sub-command that supposed to act on a specific room accepts the 
-r/--room-id optional argument which takes the room-id to act upon, 
or -a/--room_alias which takes a room alias.

to get a room-id of a room run: 
#+begin_src 
matrixcli rooms
#+end_src
outputs the following (for my account).
#+begin_example 
0 : moatazomar : !LsBUkYVYJignwCpACn:saadnpq.com
1 : mahmoudhafez : !fCXcmULzIohNQomvXD:saadnpq.com
2 : momenamr : !ocOmULdomkoJWYzXts:matrix.org
3 : elm3alem zaki : !OaBjEnLTTVqGpqrPES:matrix.org
4 : true sharing : !OSPeUVrwMKbIrLQuBX:matrix.org
#+end_example

if you didn't specify the room-id or room-alias through the command line, the program will prompt you 
with your joined rooms when it needs to. 

** listen
#+begin_src shell
matrixcli listen
#+end_src
listens forever for events and outputs incoming messages to both stdout
and os notifications, if you are running this command on a headless system
or the program failed to send notifications for some reason,
it will output events only to stdout without complaining.

you can press C-c to quit the listen mode.

there is also a systemd service installed with the program that uses =matrixcli listen=,
to enable it you can run the following.

#+begin_src shell
systemctl --user enable --now matrixcli
#+end_src 

** tail 
returns the last n messages of a room.

#+begin_src shell
matrixcli tail -h
#+end_src

#+begin_example 
usage: matrixcli tail [-h] [-r ROOM_ID | -a ROOM_ALIAS] [-f] [-n [1-100]]

optional arguments:
  -h, --help            show this help message and exit
  -r ROOM_ID, --room-id ROOM_ID
                        specify the room id
  -a ROOM_ALIAS, --room-alias ROOM_ALIAS
                        specify the room by room alias
  -f, --follow          wait for messages and print them as they come
  -n [1-100], --messages [1-100]
                        print the last specified messages
#+end_example

the option -f prints the last messages but wait for new messages
and print them as they come.

you can also send messages while in follow mode by typing the message you want to send
and hit enter to send it. 

** send
#+begin_src shell
matrixcli send --help 
#+end_src
#+begin_example
usage: matrixcli send [-h] [-r ROOM_ID | -a ROOM_ALIAS] [-t | -f] content

positional arguments:
  content

optional arguments:
  -h, --help            show this help message and exit
  -r ROOM_ID, --room-id ROOM_ID
                        specify the room id
  -a ROOM_ALIAS, --room-alias ROOM_ALIAS
                        specify the room by room alias
  -t, --text            force the program to treat the content as text message
  -f, --file            force the program to treat the content as a file
#+end_example

the send command takes the content you want to send as a positional arguments, the program first
sees if the passed text represent a file that exists in the filesystem, if so it will try to 
guess its MIME type based on the extension to correctly preview the content on the receiver's end. 
if the passed text does not represent any file on the filesystem the program will treat it as a text message.

to force the program to treat the content as a file or a text you can specify the optional arguments --file or --text.  

* Source code
The source code is distributed under GNU General Public License v3. See LICENSE.

# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
